# Generated by Django 5.2.3 on 2025-06-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20250619_0156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular User"),
                    ("owner", "Car Owner"),
                    ("admin", "Admin"),
                    ("support", "Support"),
                ],
                default="regular",
                max_length=20,
            ),
        ),
    ]
